name: Package

on:
  schedule:
    - cron: '0 0 */15 * *' # every 15 days
  workflow_dispatch:

jobs:
  package:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019,windows-2022]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Build MinimalMSVC
      run: .\build.bat

    - name: Run MinimalMSVC
      working-directory: ./bin
      run: .\MinimalMSVC.exe

    - name: Package the MSVC SDK
      working-directory: ./bin
      run: |
        $folder = Get-ChildItem -Path . -Filter "MSVC-*" | Select-Object -First 1 -ExpandProperty Name
        echo "MSVC_NAME=$folder" >> $Env:GITHUB_ENV
        cd $folder
        7z a -t7z -mx9 -md=384m -mfb=273 -ms=on -mmt=off ..\$folder.7z *

    - name: Upload the MSVC SDK
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.MSVC_NAME }}
        path: ./bin/MSVC-*.7z
